### PR TITLE
fixed the hello-signing workflow with self-generated certificate chain

### LINKED ISSUE #259: notation sign doesn't work on main branch
**Summary**
notation sign doesn't work on main branch

**Steps to reproduce issue**
- Build notation binary from main branch
- Follow the flow in https://github.com/notaryproject/notation/blob/main/docs/hello-signing.md
- Execute notation cert generate-test to create local keys and certs
- Execute notation sign --plain-http $IMAGE
- Execute notation sign $IMAGE

**Logs**

```
notation sign --plain-http $IMAGE
Incorrect Usage: flag provided but not defined: -plain-http
```

```
notation cert generate-test --default "yizha-test-certs"
notation sign $IMAGE
2022/07/22 17:05:20 certificate-chain is invalid, certificate chain must contain at least two certificates: a root and a leaf certificate
```

**Additional info**
Recommend verifying the notation sign command behavior with cobra cli implemented
https://github.com/notaryproject/notation/pull/255

### PR DESCRIPTION
**Pull request by patrickzheng200**
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

Tested with the workflow mentioned in [hello-signing](https://github.com/notaryproject/notation/blob/main/docs/hello-signing.md)
Resolves #259

### CODE REVIEW

File: cmd/notation/cert_gen.go [hunk 1]
```diff
@@ -109,39 +111,73 @@ func generateTestKey(bits int) (crypto.Signer, []byte, error) {
 	return key, keyPEM, nil
 }
 
-func generateTestSelfSignedCert(key crypto.Signer, hosts []string, expiry time.Duration) (*x509.Certificate, []byte, error) {
+func generateCert(template, parent *x509.Certificate, publicKey *rsa.PublicKey, privateKey *rsa.PrivateKey) (*x509.Certificate, []byte, error) {
```
Comment (chloeyin) [inline cmd/notation/cert_gen.go:114]: Just a question. The old code use `crypto.Signer` as a parameter, why do you change it to a concrete type `rsa.PublicKey`?  If we use an interface, then we can easily replace `rsa.GenerateKey(rand.Reader, bits)` with `ecdsa.GenerateKey(elliptic.P512(), rand.Reader)`.

Comment (patrickzheng200) [reply cmd/notation/cert_gen.go:114]: Good catch, I had the same consideration. But after a second thought, I think only using rsa is better here: according to cert generate-test's [Usage](https://github.com/notaryproject/notation/blob/bb5b49728798376a518b522f1693cf29b0376fa6/cmd/notation/cert.go#L61), it only generates RSA key as a test. So I think we should restrict the usage of this command and make it testing and demo purpose only?

Comment (chloeyin) [reply cmd/notation/cert_gen.go:114]: That makes sense :)

**Comment by JeyJeyGao** [comment]
LGTM

File: cmd/notation/cert_gen.go [hunk 2]
```diff
@@ -109,39 +111,73 @@ func generateTestKey(bits int) (crypto.Signer, []byte, error) {
...
-	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certBytes})
-	return cert, certPEM, nil
+	leafTemplate := x509.Certificate{
+		SerialNumber: serialNumber,
+		Subject: pkix.Name{
+			CommonName: hosts[0] + "LeafCA",
+		},
+		NotBefore:             now,
+		NotAfter:              now.Add(expiry),
+		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
```
Comment (binbin-li) [inline cmd/notation/cert_gen.go:173]: Do we need `KeyUsageCRLSign`?

File: cmd/notation/cert_gen.go [hunk 3]
```diff
@@ -96,7 +98,7 @@ func generateTestCert(ctx *cli.Context) error {
 	return nil
 }
 
-func generateTestKey(bits int) (crypto.Signer, []byte, error) {
```
Comment (priteshbandi) [inline cmd/notation/cert_gen.go:99]: We should reuse the code which exist for Unit tests to generate test certs:
https://github.com/notaryproject/notation-core-go/blob/main/testhelper/certificatetest.go.
It might need some refactoring.

Comment (patrickzheng200) [reply cmd/notation/cert_gen.go:99]: > We should reuse the code which exist for Unit tests to generate test certs: https://github.com/notaryproject/notation-core-go/blob/main/testhelper/certificatetest.go. It might need some refactoring.

Code updated.

File: cmd/notation/cert_gen.go (hunk 2 above)
Comment (patrickzheng200) [reply cmd/notation/cert_gen.go]: > Do we need `KeyUsageCRLSign`?

Code updated.

File: cmd/notation/cert_gen.go [hunk 4]
```diff
@@ -109,39 +110,23 @@ func generateTestKey(bits int) (crypto.Signer, []byte, error) {
...
-		return nil, nil, fmt.Errorf("failed to create certificate: %v", err)
-	}
-	cert, err := x509.ParseCertificate(certBytes)
+func generateCertPEM(rsaCertTuple *testhelper.RSACertTuple) []byte {
+	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: rsaCertTuple.Cert.Raw})
+}
+
+// generateTestRootCert generates a self-signed root certificate
+func generateTestRootCert(hosts []string, bits int) (testhelper.RSACertTuple, []byte, error) {
+	fmt.Println("testing...")
```
Comment (binbin-li) [inline cmd/notation/cert_gen.go:119]: nit: debugging log

**Comment by binbin-li** [comment]
lgtm

File: cmd/notation/cert_gen.go (hunk 4 above)
Comment (patrickzheng200) [reply cmd/notation/cert_gen.go:119]: Good catch!

**Comment by dtzar** [comment]
Per the [PR review criteria](https://github.com/notaryproject/notation/discussions/263) @notaryproject/notation-sub-group-maintainers - this is past a week old and has two approvals from official code-reviewers, so it is eligible for merge now.

@binbin-li and @JeyJeyGao - much appreciate if you can officially "approve" the PR versus just a LGTM.

**Review by binbin-li — APPROVED** [review]

**Review by shizhMSFT — APPROVED** [review]
LGTM
