### PR TITLE
fix: plugin error message

### LINKED ISSUE #704: Improve error output for notation plugin
### What is the areas you experience the issue in?

Notation CLI

### When putting an arbitrary file into the plugin folder:

```
notation plugin ls
NAME       DESCRIPTION   VERSION   CAPABILITIES   ERROR

azure-kv                           []             ERROR: response is not in JSON format. error: fork/exec /home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: exec format error, stderr:
```

**Suggestion**: changing the error to `/home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: file format is not as expected`

### When the plugin name is not followed the plugin spec:

```
NAME       DESCRIPTION   VERSION   CAPABILITIES   ERROR

azure-kv                           []             stat /home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: no such file or directory
```

**Suggest**: changing the error to `Each plugin executable must be located under $PLUGIN_DIRECTORY/{plugin-name} directory, with executable named as notation-{plugin-name}`.

### When the notation plugin executable file is not executable:

```
NAME       DESCRIPTION   VERSION   CAPABILITIES   ERROR

azure-kv                           []             ERROR: response is not in JSON format. error: fork/exec /home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: permission denied, stderr:
```

**Suggest**: changing it to `/home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: permission denied`

### When using an AMR64 arch of plugin file on an AMD64 machine:

```
notation plugin ls
NAME       DESCRIPTION   VERSION   CAPABILITIES   ERROR

azure-kv                           []             ERROR: response is not in JSON format. error: fork/exec /home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: exec format error, stderr:
```

**Suggest:** changing the error to  `/home/azureuser/.config/notation/plugins/azure-kv/notation-azure-kv: file format is not as expected`

### What did you expect to happen?

See above

### How can we reproduce it?

See above

### Describe your environment

Ubuntu 20.08

### What is the version of your Notation CLI or Notation Library?

v1.0.0-RC.7

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Examples:

**When putting an arbitrary file into the plugin folder:**
Before:
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                              
azure-trustedsigning                           []             fork/exec /home/jj/.config/notation/plugins/azure-trustedsigning/notation-azure-trustedsigning: exec format error
```

After
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                              
azure-trustedsigning                           []             plugin executable file `notation-azure-trustedsigning` is not executable. Use `notation plugin install` command to install the plugin. Please ensure that the plugin executable file is compatible with linux/amd64
```

**When the plugin name is not followed the plugin spec:**
Before
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                                                                                                                        
azure-trustedsigning                           []             plugin executable file is either not found or inaccessible: stat /home/jj/.config/notation/plugins/azure-trustedsigning/notation-azure-trustedsigning: no such file or directory
```

After
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                                                                                                                        
azure-trustedsigning                           []             plugin executable file `notation-azure-trustedsigning` not found. Use `notation plugin install` command to install the plugin. Each plugin executable must be placed in the $PLUGIN_DIRECTORY/{plugin-name} directory, with the executable named as 'notation-{plugin-name}''
```

**When the notation plugin executable file is not executable:**
Before/After are the same
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                               
azure-trustedsigning                           []             fork/exec /home/jj/.config/notation/plugins/azure-trustedsigning/notation-azure-trustedsigning: permission denied
```

**When using an AMR64 arch of plugin file on an AMD64 machine:**
Before:
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                              
azure-trustedsigning                           []             fork/exec /home/jj/.config/notation/plugins/azure-trustedsigning/notation-azure-trustedsigning: exec format error
```

After:
```
NAME                   DESCRIPTION   VERSION   CAPABILITIES   ERROR                                                                                                                                                                                                                              
azure-trustedsigning                           []             plugin file `notation-azure-trustedsigning` is not executable. Use `notation plugin install` command to install the plugin. Please ensure that the plugin executable file is compatible with linux/amd64
```

Resolves #704

### CODE REVIEW

**Review by Two-Hearts — COMMENTED** [review]
Can you provide a before-and-after comparison regarding this change?

**Comment by JeyJeyGao** [comment]
> Can you provide a before-and-after comparison regarding this change?

Updated.

**Review by Two-Hearts — CHANGES_REQUESTED** [review]
It seems that the changes in this PR does not align with the discussion in the original issue. Will review this PR once everyone is on the same page. 

cc: @FeynmanZhou

**Comment by JeyJeyGao** [comment]
> It seems that the changes in this PR does not align with the discussion in the original issue. Will review this PR once everyone is on the same page.
> 
> cc: @FeynmanZhou

Yes, the change may not be exactly as originally proposed, as I believe we need to retain the original Go built-in error for easier error investigation. I have added an additional recommendation message to improve the error message. Please have a look, @FeynmanZhou.

File: cmd/notation/plugin/list.go [hunk 1]
```diff
@@ -68,7 +71,27 @@ func listPlugins(command *cobra.Command) error {
...
+// userFriendlyError optimizes the error message for the user.
+func userFriendlyError(err error) error {
+	if err == nil {
+		return nil
+	}
+	var pathError *fs.PathError
+	if errors.As(err, &pathError) {
+		// for plugin does not exist
+		if errors.Is(pathError, fs.ErrNotExist) {
+			return fmt.Errorf("%w. Each plugin executable must be located under $PLUGIN_DIRECTORY/{plugin-name} directory, with executable named as notation-{plugin-name}", pathError)
```
Comment (FeynmanZhou) [inline cmd/notation/plugin/list.go:88]:
```suggestion
			return fmt.Errorf("%w. Each plugin executable must be placed in the $PLUGIN_DIRECTORY/{plugin-name} directory, with the executable named as 'notation-{plugin-name}'", pathError)
```

**Comment by FeynmanZhou** [comment]
> It seems that the changes in this PR does not align with the discussion in the original issue. Will review this PR once everyone is on the same page.
> 
> cc: @FeynmanZhou

The error message in original issue is no longer valid. Junjie revisited the latest plugin-related error message and proposed this PR. We just need to make sure these error message follow the [Notation CLI Error Handling and Message Guideline](https://github.com/notaryproject/notation/blob/main/specs/error-handling-guideline.md).

File: cmd/notation/plugin/list.go (hunk 1 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go]: Updated.

**Review by FeynmanZhou — DISMISSED** [review]
LGTM. Thanks @JeyJeyGao

**Review by shizhMSFT — DISMISSED** [review]
LGTM

File: cmd/notation/plugin/list.go [hunk 2]
```diff
@@ -68,7 +71,27 @@ func listPlugins(command *cobra.Command) error {
...
+
+// userFriendlyError optimizes the error message for the user.
+func userFriendlyError(err error) error {
+	if err == nil {
+		return nil
+	}
+	var pathError *fs.PathError
+	if errors.As(err, &pathError) {
+		// for plugin does not exist
+		if errors.Is(pathError, fs.ErrNotExist) {
```
Comment (Two-Hearts) [inline cmd/notation/plugin/list.go:87]: For `plugin list` command, this error doesn't really make sense? The command aims to list any existing plugin. So how would a non-existing plugin be listed out with this error? 
In other words, logically speaking, this error should never be triggered by the command.

File: cmd/notation/plugin/list.go [hunk 3]
```diff
@@ -68,7 +71,27 @@ func listPlugins(command *cobra.Command) error {
...
+			return fmt.Errorf("%w. Each plugin executable must be placed in the $PLUGIN_DIRECTORY/{plugin-name} directory, with the executable named as 'notation-{plugin-name}'", pathError)
```
Comment (Two-Hearts) [inline cmd/notation/plugin/list.go:88]: Do we need to return the error, because from your example shown in the PR description, the error itself is verbose and provides very little information.
In addition, can we mention `notation plugin install` command in the error msg as an actionable next step for users?

**Review by Two-Hearts — CHANGES_REQUESTED** [review]

File: cmd/notation/plugin/list.go [hunk 4]
```diff
@@ -68,7 +71,27 @@ func listPlugins(command *cobra.Command) error {
...
+		}
+
+		// for plugin is not executable
+		if pathError.Op == "fork/exec" && pathError.Err == syscall.Errno(8) {
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go]: Updated to check ` pathError.Err == syscall.ENOEXEC` directly.

File: cmd/notation/plugin/list.go (hunk 2 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:87]: This error may occur when a user manually installs a plugin with an invalid plugin name. For example, if the user has the plugin installed in `~/.config/notation/plugin/azure-kv/azure-kv`, we need an error message to indicate that `notation-azure-kv` is not found.

File: cmd/notation/plugin/list.go (hunk 3 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go]: Updated error message.

**Review by FeynmanZhou — APPROVED** [review]
LGTM

File: cmd/notation/plugin/list.go (hunk 2 above)
Comment (Two-Hearts) [reply cmd/notation/plugin/list.go:87]: I see. Then we should improve the error message `stat ...: no such file or directory` to be more user friendly.

Consider a less verbose message:
`Plugin executable file <notation-xxx> not found. Use `notation plugin install` command to install the plugin.`

Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:91]: Updated.

File: cmd/notation/plugin/list.go [hunk 5]
```diff
@@ -68,7 +71,31 @@ func listPlugins(command *cobra.Command) error {
...
+			executableName += ".exe"
+		}
+		// for plugin does not exist
+		if errors.Is(pathError, fs.ErrNotExist) {
+			return fmt.Errorf("%w. Plugin executable file `%s` not found. Use `notation plugin install` command to install the plugin. Each plugin executable must be placed in the $PLUGIN_DIRECTORY/{plugin-name} directory, with the executable named as 'notation-{plugin-name}'", pathError, executableName)
+		}
+
+		// for plugin is not executable
+		if pathError.Err == syscall.ENOEXEC {
+			return fmt.Errorf("%w. Please ensure that the plugin executable file is compatible with %s/%s", pathError, runtime.GOOS, runtime.GOARCH)
```
Comment (Two-Hearts) [inline cmd/notation/plugin/list.go:97]:
```suggestion
			return fmt.Errorf("Plugin file `%s` is not executable. Use `notation plugin install` command to install the plugin. Please ensure that the plugin executable file is compatible with %s/%s", pluginFileName, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/list.go [hunk 6]
```diff
@@ -68,7 +71,31 @@ func listPlugins(command *cobra.Command) error {
...
 }
+
+// userFriendlyError optimizes the error message for the user.
+func userFriendlyError(pluginName string, err error) error {
+	if err == nil {
+		return nil
+	}
+	var pathError *fs.PathError
+	if errors.As(err, &pathError) {
+		executableName := "notation-" + pluginName
```
Comment (Two-Hearts) [inline cmd/notation/plugin/list.go:86]:
```suggestion
		pluginFileName:= plugin.BinaryPrefix + pluginName
```

[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:86]: Updated.

Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:86]: Updated.

File: cmd/notation/plugin/list.go [hunk 7]
```diff
@@ -68,7 +71,31 @@ func listPlugins(command *cobra.Command) error {
...
+		if runtime.GOOS == "windows" {
+			executableName += ".exe"
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:88]: Updated.

File: cmd/notation/plugin/list.go [hunk 8]
```diff
@@ -68,7 +71,31 @@ func listPlugins(command *cobra.Command) error {
...
+		}
+		// for plugin does not exist
+		if errors.Is(pathError, fs.ErrNotExist) {
+			return fmt.Errorf("%w. Plugin executable file `%s` not found. Use `notation plugin install` command to install the plugin. Each plugin executable must be placed in the $PLUGIN_DIRECTORY/{plugin-name} directory, with the executable named as 'notation-{plugin-name}'", pathError, executableName)
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:92]: Updated.

File: cmd/notation/plugin/list.go (hunk 5 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go:97]: Updated.

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM
