### PR TITLE
fix: improve error message for --signature-format flag

### LINKED ISSUE #868: Improve error logs for notation sign
### What is not working as expected?

This issue summarizes the error messages of `notation sign` that I suggest improving in v1.1.x. 

### Sign an artifact with an non-existing signing key in a key vault

Current behavior and output:

```
$ notation sign localhost:5000/test-repo:v1  --signature-format cose --plugin wabbitnetworks-kv --id https://feynman-kv.vault.wabbit.net/keys/feynmankv-networks-io/6670ffa5cb694c49b1e0a6bb6bdefaaa
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v1) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Error: describe-key command failed: ERROR: A certificate with (name/id) feynmankv-networks-io/versions/6670ffa5cb694c49b1e0a6bb6bdefaaa was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.wabbit.net/fwlink/?linkid=2125182
Status: 404 (Not Found)
ErrorCode: CertificateNotFound

Content:
{"error":{"code":"CertificateNotFound","message":"A certificate with (name/id) feynmankv-networks-io/versions/6670ffa5cb694c49b1e0a6bb6bdefaaa was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.wabbit.net/fwlink/?linkid=2125182"}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: eastus
x-ms-client-request-id: a2923244-ed47-461b-9dc1-d0b9f4202788
x-ms-request-id: 96103d99-c372-449f-adba-8d24b7d5da7e
x-ms-keyvault-service-version: 1.9.1116.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=20.65.162.175;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Wed, 13 Dec 2023 07:27:33 GMT
Content-Length: 376
Content-Type: application/json; charset=utf-8
Expires: -1
```

Suggested error message:

```
$ notation sign localhost:5000/test-repo:v1  --signature-format cose --plugin wabbitnetworks-kv --id https://feynman-kv.vault.wabbit.net/keys/feynmankv-networks-io/6670ffa5cb694c49b1e0a6bb6bdefaaa
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v1) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Error response from server: A certificate with (name/id) feynmankv-networks-io/versions/6670ffa5cb694c49b1e0a6bb6bdefaaa was not found in this key vault. 
Please make sure the certificate is available in the key vault. Use "--verbose" to see detailed logs.
```

### Sign an artifact with an error signature format parameter

Current behavior and output:

```
$ notation sign localhost:5000/test-repo:v1  --signature-format cosee
Error: signature format "cosee" not supported
```

Suggested error message:

```
$ notation sign localhost:5000/test-repo:v1  --signature-format dsse
Error: signature format "dsse" not supported
Please use the supported signature envelope format "jws" or "cose"
```

### What did you expect to happen?

See above

### How can we reproduce it?

See above

### Describe your environment

Linux Ubuntu 22.06

### What is the version of your Notation CLI or Notation Library?

v1.0.1

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Previous error message:
```
$ notation sign localhost:5000/hello-app:v1 --plugin azure-kv --id https://x.vault.azure.net/certificates/self-signed-pem/xxx --signature-format xxx
Error: signature format "xxx" not supported
```

Improved error message:
```
$ notation sign localhost:5000/hello-app:v1 --plugin azure-kv --id https://x.vault.azure.net/certificates/self-signed-pem/xxx --signature-format xxx
Error: signature format "xxx" not supported
Please use the supported signature envelope format "jws" or "cose"
```

Test(not related to the fix):
- added unit test and e2e test to reach codecov target 

Resolves #868
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM

File: internal/envelope/envelope.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func GetEnvelopeMediaType(sigFormat string) (string, error) {
 	case COSE:
 		return cose.MediaTypeEnvelope, nil
 	}
-	return "", fmt.Errorf("signature format %q not supported", sigFormat)
+	return "", fmt.Errorf("signature format %q not supported\nPlease use the supported signature envelope format \"jws\" or \"cose\"", sigFormat)
```
Comment (Two-Hearts) [inline internal/envelope/envelope.go:49]: This looks good, but maybe we can make it a little bit more concise?
```suggestion
	return "", fmt.Errorf("signature format %q not supported\nSupported signature envelope formats are \"jws\" and \"cose\"", sigFormat)
```

Comment (FeynmanZhou) [reply internal/envelope/envelope.go:49]: Both look good and user friendly to me. @JeyJeyGao 's description seems much more actionable and straightforward. to users.

Comment (Two-Hearts) [reply internal/envelope/envelope.go:49]: > Both look good and user friendly to me. @JeyJeyGao 's description seems much more actionable and straightforward. to users.

@FeynmanZhou Asked ChatGPT for suggestion:
```
Both options are grammatically correct and convey the same meaning, but the second option is more concise and easier to understand. Therefore, I would recommend using the second option: "Supported signature envelope formats are 'jws' and 'cose'."`
```
(the question was 'which one is better for an error message?')

**Review by shizhMSFT — APPROVED** [review]
LGTM

File: internal/envelope/envelope.go (hunk 1 above)
Comment (JeyJeyGao) [reply internal/envelope/envelope.go]: Updated.

**Review by Two-Hearts — APPROVED** [review]
LGTM

(the codecov failed though)

**Review by priteshbandi — DISMISSED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
