### PR TITLE
test: add e2e test cases for flag `--insecure-registry`

### LINKED ISSUE #633: Missing e2e test cases for flag `--plain-http`
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

Missing e2e test cases for flag `--plain-http`, which exists for the following commands. This flag allows users to establish insecure connections to registries, so it should be tested properly.

- notation sign
- notation verify
- notation list
- notation inspect
- notation login

### What did you expect to happen?

Add e2e test cases for flag `--plain-http` used by all notation CLI commands 

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation CLI v1.0.0-rc.3

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Feature:
- add E2E testing TLS support for Github Action environment

Test:
- added `--insecure-registry` test for sign, verify, inspect, list

> **Note** `login` command E2E test cases are not included in the PR because it needs to setup credential store in Github Action and should be done in another PR. Added an issue to track it #680 

Resolves #633 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

File: test/e2e/internal/notation/registry.go [hunk 1]
```diff
@@ -19,9 +19,16 @@ import (
...
-	Host     string
+	// Host is the registry host.
+	Host string
+	// Username is the username to access the registry.
 	Username string
+	// Password is the password to access the registry.
 	Password string
+	// DomainHost is an registry host for testing --plain-http flag.
+	// if the host is localhost, notation make all connection as plain http.
+	// if the host is not localhost, notation make all connection as https.
```
Comment (priteshbandi) [inline test/e2e/internal/notation/registry.go:30]: Is this statement true? even if host is not localhost notation can interact with registry using http.

File: test/e2e/internal/notation/init.go [hunk 2]
```diff
@@ -23,6 +23,7 @@ const (
 	envKeyRegistryHost       = "NOTATION_E2E_REGISTRY_HOST"
 	envKeyRegistryUsername   = "NOTATION_E2E_REGISTRY_USERNAME"
 	envKeyRegistryPassword   = "NOTATION_E2E_REGISTRY_PASSWORD"
+	envKeyDomainRegistryHost = "NOTATION_E2E_DOMAIN_REGISTRY_HOST"
```
Comment (priteshbandi) [inline test/e2e/internal/notation/init.go:26]: How is this different from `NOTATION_E2E_REGISTRY_HOST` ?

File: test/e2e/suite/command/inspect.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+		})
+	})
+
+	It("all signatures of an image with --insecure-registry flag", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
+
+			notation.Exec("inspect", "--insecure-registry", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(inspectSuccessfully...)
```
Comment (priteshbandi) [inline test/e2e/suite/command/inspect.go:60]: How are we verifying communication indeed happened over https  and http in case of --insecure-registry usecase.

File: test/e2e/internal/notation/registry.go [hunk 4]
```diff
@@ -19,9 +19,16 @@ import (
...
 
 type Registry struct {
-	Host     string
+	// Host is the registry host.
+	Host string
+	// Username is the username to access the registry.
 	Username string
+	// Password is the password to access the registry.
 	Password string
+	// DomainHost is an registry host for testing --plain-http flag.
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply test/e2e/internal/notation/registry.go]: Thanks!

File: test/e2e/internal/notation/init.go (hunk 2 above)
Comment (JeyJeyGao) [reply test/e2e/internal/notation/init.go:26]: NOTATION_E2E_DOMAIN_REGISTRY_HOST is a registry host, separate from localhost, used for testing the --insecure-registry flag.

File: test/e2e/suite/command/inspect.go (hunk 3 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/inspect.go]: You can read the testing debug log from  `Run e2e tests` step of `build` Github Actions

Comment (JeyJeyGao) [reply test/e2e/suite/command/inspect.go]: For example: https://github.com/notaryproject/notation/actions/runs/5063834914/jobs/9090861035?pr=679

Comment (priteshbandi) [reply test/e2e/suite/command/inspect.go]: yes but how are we validating this in test? For e.g. in future if someone introduce a bug where `--insecure-registry` is getting ignored and notation is using https, how will this test catch the issue?

File: test/e2e/suite/command/sign.go [hunk 5]
```diff
@@ -150,4 +150,24 @@ var _ = Describe("notation sign", func() {
 				MatchErrContent(expectedErrMsg)
 		})
 	})
+
+	It("with TLS by digest", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", "-d", artifact.DomainReferenceWithDigest()).
```
Comment (Two-Hearts) [inline test/e2e/suite/command/sign.go:156]: Just curious, why do we need to test with the `-d` flag enabled?

**Review by shizhMSFT — DISMISSED** [review]
LGTM

File: test/e2e/suite/command/sign.go [hunk 6]
```diff
@@ -150,4 +150,24 @@ var _ = Describe("notation sign", func() {
...
+
+			OldNotation().Exec("verify", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(VerifySuccessfully)
+		})
+	})
+
+	It("with --insecure-registry by digest", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", "-d", "--insecure-registry", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
```
[the remark this answers is not in the document]
Comment (priteshbandi) [reply test/e2e/suite/command/sign.go:167]: This will also resolve my comment https://github.com/notaryproject/notation/pull/679#discussion_r1203681532

File: test/e2e/suite/command/inspect.go (hunk 3 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/inspect.go]: Got it. Updated to include the assertion for HTTP and HTTPS request.

File: test/e2e/suite/command/sign.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply test/e2e/suite/command/sign.go]: Updated to include the assertion for HTTP and HTTPS request.

File: test/e2e/suite/command/verify.go [hunk 7]
```diff
@@ -121,4 +121,24 @@ var _ = Describe("notation verify", func() {
...
+				MatchKeyWords(VerifySuccessfully)
+		})
+	})
+
+	It("with --insecure-registry by digest", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
+
+			notation.Exec("verify", "-d", "--insecure-registry", artifact.DomainReferenceWithDigest(), "-v").
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply test/e2e/suite/command/verify.go:144]: Updated to include the assertion for HTTP and HTTPS request.

File: test/e2e/suite/command/sign.go (hunk 5 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/sign.go:156]: To print the request log for ensuring the connection is HTTP or HTTPS

File: test/e2e/suite/command/verify.go [hunk 8]
```diff
@@ -121,4 +121,32 @@ var _ = Describe("notation verify", func() {
 				MatchErrKeyWords(expectedErrMsg)
 		})
 	})
+
+	It("with TLS by digest", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
+
+			notation.Exec("verify", "-d", artifact.DomainReferenceWithDigest(), "-v").
```
Comment (Two-Hearts) [inline test/e2e/suite/command/verify.go:130]: nit:
For this one, since we already turned on "-d", we can remove "-v".
```suggestion
			notation.Exec("verify", "-d", artifact.DomainReferenceWithDigest()).
```

File: test/e2e/suite/command/verify.go [hunk 9]
```diff
@@ -121,4 +121,32 @@ var _ = Describe("notation verify", func() {
...
+				NotMatchErrKeyWords("http://notation-e2e.registry.io")
+		})
+	})
+
+	It("with --insecure-registry by digest", func() {
+		HostInGithubAction(BaseOptions(), func(notation *utils.ExecOpts, artifact *Artifact, vhost *utils.VirtualHost) {
+			notation.Exec("sign", artifact.DomainReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
+
+			notation.Exec("verify", "-d", "--insecure-registry", artifact.DomainReferenceWithDigest(), "-v").
```
Comment (Two-Hearts) [inline test/e2e/suite/command/verify.go:144]: nit:
Same here.
```suggestion
			notation.Exec("verify", "-d", "--insecure-registry", artifact.DomainReferenceWithDigest()).
```

File: test/e2e/internal/utils/matcher.go [hunk 10]
```diff
@@ -48,6 +54,15 @@ func (m *Matcher) MatchErrKeyWords(keywords ...string) *Matcher {
 	return m
 }
 
+// NotMatchKeyWords guarantees that the given keywords do not match with
```
Comment (Two-Hearts) [inline test/e2e/internal/utils/matcher.go:57]: nit:
The func doc dose not align with the func name.

File: test/e2e/internal/utils/matcher.go [hunk 11]
```diff
@@ -48,6 +54,15 @@ func (m *Matcher) MatchErrKeyWords(keywords ...string) *Matcher {
...
+// the stderr.
+func (m *Matcher) NotMatchErrKeyWords(keywords ...string) *Matcher {
```
Comment (Two-Hearts) [inline test/e2e/internal/utils/matcher.go:59]: nit:
suggesting a new name of the func.
```suggestion
func (m *Matcher) NoMatchErrKeyWords(keywords ...string) *Matcher {
```

File: test/e2e/internal/notation/registry.go [hunk 12]
```diff
@@ -101,6 +111,10 @@ func (r *Artifact) ReferenceWithDigest() string {
 	return fmt.Sprintf("%s/%s@%s", r.Host, r.Repo, r.Digest)
 }
 
+func (r *Artifact) DomainReferenceWithDigest() string {
```
Comment (Two-Hearts) [inline test/e2e/internal/notation/registry.go:114]: nit:
Need a func doc for this method.

File: test/e2e/suite/command/verify.go (hunk 8 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/verify.go]: Removed.

File: test/e2e/suite/command/verify.go (hunk 9 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/verify.go]: Removed.

File: test/e2e/internal/utils/matcher.go (hunk 10 above)
Comment (JeyJeyGao) [reply test/e2e/internal/utils/matcher.go]: Updated.

File: test/e2e/internal/utils/matcher.go (hunk 11 above)
Comment (JeyJeyGao) [reply test/e2e/internal/utils/matcher.go]: Updated.

File: test/e2e/internal/notation/registry.go (hunk 12 above)
Comment (JeyJeyGao) [reply test/e2e/internal/notation/registry.go:116]: Updated.

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM
