### PR TITLE
fix(test): E2E test cases for OCI layout

### LINKED ISSUE #693: OCI layout E2E test cases issue
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

The OCI layout E2E test cases share the same OCI layout folder, which is not expected.

### What did you expect to happen?

For each test case, generate an isolated OCI layout.

### How can we reproduce it?

Run `make e2e`, then you will see that many blobs generated in the `./test/e2e/testdata/oci-layout` directory

### Describe your environment

Linux x64

### What is the version of your Notation CLI or Notation Library?

Notation RC6

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Feat:
- add E2E test framework oci layout support: generate isolated oci layout dynamically for each test case

Fix:
- update oci layout test to use isolated oci layout (previsouly the oci layout is shared by multiple test cases)
- the assertion target for TLS and --insecure-registry test cases

Test:
- added new test cases for `notation list  --oci-layout`

Resolves #693 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

File: test/e2e/suite/command/list.go
Comment (Two-Hearts) [inline test/e2e/suite/command/list.go:1]: Let's add test cases of `notation list --oci-layout`. (Currently, Notation supports Sign/List/Verify on oci layout.)

Comment (JeyJeyGao) [reply test/e2e/suite/command/list.go:1]: Added test cases for `notation list  --oci-layout`

File: test/e2e/suite/command/list.go [hunk 1]
```diff
@@ -50,4 +50,24 @@ var _ = Describe("notation list", func() {
...
+
+	It("all signatures of an oci-layout", func() {
+		HostWithOCILayout(BaseOptionsWithExperimental(), func(notation *utils.ExecOpts, ociLayout *OCILayout, vhost *utils.VirtualHost) {
+			notation.Exec("sign", "--oci-layout", ociLayout.ReferenceWithDigest()).
+				MatchKeyWords(SignSuccessfully)
+
+			notation.Exec("list", "--oci-layout", ociLayout.ReferenceWithDigest()).
+				MatchKeyWords(
+					"└── application/vnd.cncf.notary.signature",
+					"└── sha256:",
```
Comment (Two-Hearts) [inline test/e2e/suite/command/list.go:62]: Can we match the digest instead of just `sha256`. On success, the signature generated by `sign` should be listed out.

Comment (JeyJeyGao) [reply test/e2e/suite/command/list.go]: Updated to use a signed oci-layout.

**Review by Two-Hearts — COMMENTED** [review]
I notice that `testdata` are still in oci artifact manifest type. We'd better update them to oci image manifest? Otherwise, LGTM.

**Comment by JeyJeyGao** [comment]
> I notice that `testdata` are still in oci artifact manifest type. We'd better update them to oci image manifest? Otherwise, LGTM.

This PR is for fixing oci layout. #668 will be done in another PR.

**Review by Two-Hearts — DISMISSED** [review]
LGTM

**Review by shizhMSFT — DISMISSED** [review]
LGTM

File: test/e2e/suite/command/list.go [hunk 2]
```diff
@@ -50,4 +50,26 @@ var _ = Describe("notation list", func() {
...
+
+			notation.Exec("list", "--oci-layout", ociLayout.ReferenceWithDigest()).
+				MatchKeyWords(
+					"└── application/vnd.cncf.notary.signature",
+					"└── sha256:273243a7a64e9312761ca0aa8f43b6ba805e677a561558143b6e92981c487339",
+				)
+		})
+	})
+
+	It("none signature of an oci-layout", func() {
```
Comment (priteshbandi) [inline test/e2e/suite/command/list.go:69]:
```suggestion
	It("oci-layout with no signature", func() {
```

**Review by priteshbandi — DISMISSED** [review]
LGTM with a nit

File: test/e2e/suite/command/list.go (hunk 2 above)
Comment (JeyJeyGao) [reply test/e2e/suite/command/list.go]: Updated.

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by Two-Hearts — APPROVED** [review]
LGTM
