### PR TITLE
fix: blob policy command messages with docs

### LINKED ISSUE #1134: Update blob spec
### What is not working as expected?

The Blob specification documents contain some content that is inconsistent with the implementation and need to be updated.

### What did you expect to happen?

1. the command help doc need to be updated. Related link: https://github.com/notaryproject/notation/pull/1126#discussion_r1903697983

### How can we reproduce it?

N

### Describe your environment

N

### What is the version of your Notation CLI or Notation Library?

main branch

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Fix:
- simplified `blob policy show` codes
- improved help docs and error messages
- improved docs
- printed imported blob trust policy file path

Resolves #1134

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

File: cmd/notation/blob/policy/import.go [hunk 1]
```diff
@@ -34,10 +34,10 @@ func importCmd() *cobra.Command {
 	var opts importOpts
 	command := &cobra.Command{
 		Use:   "import [flags] <file_path>",
-		Short: "Import blob trust policy configuration from a JSON file",
-		Long: `Import blob trust policy configuration from a JSON file.
+		Short: "Import blob trust policy file from a JSON file",
+		Long: `Import blob trust policy file from a JSON file.
 
-Example - Import blob trust policy configuration from a file:
+Example - Import blob trust policy file from a file:
```
Comment (Two-Hearts) [inline cmd/notation/blob/policy/import.go:40]: Can we make this sentence more meaningful? Something like:
```suggestion
Example - Import blob trust policy configuration from a file and store as `trustpolicy.blob.json`:
```

File: cmd/notation/blob/policy/import.go [hunk 2]
```diff
@@ -34,10 +34,10 @@ func importCmd() *cobra.Command {
 	var opts importOpts
 	command := &cobra.Command{
 		Use:   "import [flags] <file_path>",
-		Short: "Import blob trust policy configuration from a JSON file",
-		Long: `Import blob trust policy configuration from a JSON file.
+		Short: "Import blob trust policy file from a JSON file",
+		Long: `Import blob trust policy file from a JSON file.
```
Comment (Two-Hearts) [inline cmd/notation/blob/policy/import.go:38]: This change is not necessary though..

File: cmd/notation/blob/policy/show.go [hunk 3]
```diff
@@ -29,13 +28,13 @@ import (
 func showCmd() *cobra.Command {
 	command := &cobra.Command{
 		Use:   "show [flags]",
-		Short: "Show blob trust policy configuration",
-		Long: `Show blob trust policy configuration.
+		Short: "Show blob trust policy file",
+		Long: `Show blob trust policy file.
```
Comment (Two-Hearts) [inline cmd/notation/blob/policy/show.go:32]: I don't think this change is necessary, the user won't know the file name or the file location from this description anyway.

File: cmd/notation/blob/policy/show.go [hunk 4]
```diff
@@ -29,13 +28,13 @@ import (
...
 
-Example - Show current blob trust policy configuration:
+Example - Show current blob trust policy file:
   notation blob policy show
 
-Example - Save current blob trust policy configuration to a file:
+Example - Save current blob trust policy file to a file:
```
Comment (Two-Hearts) [inline cmd/notation/blob/policy/show.go:37]: Same here, please make it more meaningful.

File: cmd/notation/blob/policy/import.go (hunk 2 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/import.go:38]: Yes, I think both of them work. Just to be consistent with the OCI policy command.

File: cmd/notation/blob/policy/import.go (hunk 1 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/import.go]: Updated.

File: cmd/notation/blob/policy/show.go (hunk 3 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/show.go]: Updated to mention the file name. This change is also to be consistent with OCI policy command.

File: cmd/notation/blob/policy/show.go (hunk 4 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/show.go]: Updated.

File: cmd/notation/blob/policy/import.go (hunk 2 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/import.go]: Updated.

File: cmd/notation/blob/policy/show.go (hunk 3 above)
Comment (JeyJeyGao) [reply cmd/notation/blob/policy/show.go]: Updated.

File: cmd/notation/blob/policy/import.go [hunk 5]
```diff
@@ -62,21 +62,21 @@ func runImport(opts importOpts) error {
 	// read configuration
 	policyJSON, err := os.ReadFile(opts.filePath)
 	if err != nil {
-		return fmt.Errorf("failed to read blob trust policy file: %w", err)
+		return fmt.Errorf("failed to read blob trust policy configuration: %w", err)
```
Comment (Two-Hearts) [inline cmd/notation/blob/policy/import.go:65]: Let's call it a `file` as it hasn't been imported to Notation yet.

Comment (JeyJeyGao) [reply cmd/notation/blob/policy/import.go:65]: Updated.

**Review by shizhMSFT — APPROVED** [review]
LGTM
