### PR TITLE
fix: fixing cert command

### LINKED ISSUE #622: `notation cert delete` confirms deletion without doing anything
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

`notation cert delete` prints out message that a cert is deleted although such cert does not exist in the store at all.
```
$ notation cert delete --type ca --store nonexistent --all
Are you sure you want to delete all certificate in "nonexistent" of type "ca"? [y/N] y
Successfully deleted /Users/toddysm/Library/Application Support/notation/truststore/x509/ca/nonexistent
```

### What did you expect to happen?

To print out that there is no such cert.

### How can we reproduce it?

Use `notation cert delete` with non-existent store

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

```
$ notation version                                                          
Notation - a tool to sign and verify artifacts.

Version:     1.0.0-rc.4.230405
Go version:  go1.20.2
Git commit:  b008e79328df9ac2789c7e6524741f8a32d33d78
```

### PR DESCRIPTION
**Pull request by patrickzheng200**
This PR aims to resolve #622.
It also adds MarkFlagRequired() to required flags in notation cert command.

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

File: cmd/notation/internal/truststore/truststore.go [hunk 1]
```diff
@@ -127,59 +127,54 @@ func showCert(cert *x509.Certificate) {
...
+	if err != nil {
+		return err
+	}
+	if !confirmed {
+		return nil
+	}
+	if _, err := os.Stat(path); err != nil {
+		return err
+	}
+	if err = os.RemoveAll(path); err != nil {
```
Comment (priteshbandi) [inline cmd/notation/internal/truststore/truststore.go:172]:
```suggestion
	if err = os.Remove(path); err != nil {
```

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM
