### PR TITLE
fix: improve error message for plugin

### LINKED ISSUE #867: Improve notation plugin error message
### What is not working as expected?

This issue summarizes the error messages of `notation plugin` that I suggest improving in v1.1.x. 

## Negative case: install a plugin on a non-matching CPU architecture machine

I installed Notation AKV plugin (Linux_arm64 version) on an Linux_amd64 machine with Notation v1.1.0 (main branch). The error response is empty in stderr as follows. This empty error response also exists when I installed the AWS Signer plugin in a mismatched Arch.

```
$ notation plugin install --file notation-azure-kv_1.0.1_linux_arm64.tar.gz
···
Error: plugin installation failed: failed to get metadata of new plugin: ERROR: response is not in JSON format. error: fork/exec /tmp/notation-plugin1835003109/notation-azure-kv: exec format error, stderr:
```

### What did you expect to happen?

Suggested change:

By following the [Notation error message guidance](https://github.com/notaryproject/notation/pull/834/files), `notation` should prompt users that the architecture of the installing plugin is not matched with the machine:

```
$ notation plugin install --file notation-azure-kv_1.0.1_linux_arm64.tar.gz
···
Error: plugin installation failed: failed to get metadata of new plugin. exec format error, stderr: non-matching CPU architecture
Use a matched architecture of the plugin and try to install it again
```

Or even give a much intelligent prompt with a solution:

```
$ notation plugin install --file notation-azure-kv_1.0.1_linux_arm64.tar.gz
···
Error: plugin installation failed: failed to get metadata of new plugin. exec format error, non-matching CPU architecture
Use a matched architecture linux/amd64 of the plugin and try to install it again
```

### How can we reproduce it?

See above

### Describe your environment

Linux, Golang 21.06

### What is the version of your notation-go Library?

v1.1.0

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Resolves #867 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by Two-Hearts — CHANGES_REQUESTED** [review]
Blocking the merge as I'm building from this branch and testing the new error messages locally.

**Comment by Two-Hearts** [comment]
When running command on a malformed plugin executable file on `Windows`:
`./notation.exe plugin install --file ./malformed-plugin/azure-kv/notation-azure-kv.exe`, the command returns following error message:
```
Error: plugin installation failed: failed to get metadata of new plugin: failed to execute the get-plugin-metadata command for plugin azure-kv: fork/exec ./malformed-plugin/azure-kv/notation-azure-kv.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher..
Please ensure the plugin is executable and meet the installation requirements on the windows/amd64.
```
On `linux`:
```
Error: plugin installation failed: failed to get metadata of new plugin: failed to execute the get-plugin-metadata command for plugin azure-kv: fork/exec test-plugin/malformed-plugin/azure-kv/notation-azure-kv: exec format error.
Please ensure the plugin is executable and meet the installation requirements on the linux/amd64.
```
These error messages are quite verbose though, can we improve them?

File: cmd/notation/plugin/install.go [hunk 1]
```diff
@@ -330,6 +331,19 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
...
+			var errPath *os.PathError
+			if errors.As(errExeFile, &errPath) && errPath.Op == "fork/exec" {
+				return fmt.Errorf("%w.\nPlease ensure the plugin is executable and meet the installation requirements on the %s/%s.", errExeFile, runtime.GOOS, runtime.GOARCH)
+			}
+		}
+
+		var errMalformedPlugin *plugin.PluginMalformedError
+		if errors.As(err, &errMalformedPlugin) {
+			return fmt.Errorf("%w.\nPlease ensure the installation of the plugin for %s/%s, and make sure that the plugin adheres to the Notation plugin requirements.", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
+		}
```
Comment (Two-Hearts) [inline cmd/notation/plugin/install.go:350]: For an external user running command `notation plugin install`, they might not be the plugin publisher, and thus, they might not know how to determine/fix whether a plugin adheres to the `Notation plugin requirements`. (They might not even know the existence of `Notation plugin requirement`)
```suggestion
		var errMalformedPlugin *plugin.PluginMalformedError
		if errors.As(err, &errMalformedPlugin) {
			return fmt.Errorf("%w.\nPlease ensure to install the plugin for %s/%s. Contact the plugin publisher if the plugin executable file is malformed", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
		}
```

**Comment by JeyJeyGao** [comment]
> When running command on a malformed plugin executable file on `Windows`: `./notation.exe plugin install --file ./malformed-plugin/azure-kv/notation-azure-kv.exe`, the command returns following error message:
> 
> ```
> Error: plugin installation failed: failed to get metadata of new plugin: failed to execute the get-plugin-metadata command for plugin azure-kv: fork/exec ./malformed-plugin/azure-kv/notation-azure-kv.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher..
> Please ensure the plugin is executable and meet the installation requirements on the windows/amd64.
> ```
> 
> On `linux`:
> 
> ```
> Error: plugin installation failed: failed to get metadata of new plugin: failed to execute the get-plugin-metadata command for plugin azure-kv: fork/exec test-plugin/malformed-plugin/azure-kv/notation-azure-kv: exec format error.
> Please ensure the plugin is executable and meet the installation requirements on the linux/amd64.
> ```
> 
> These error messages are quite verbose though, can we improve them? (contents starting with `fork/exec` are already in the DEBUG log)

Updated to:
```
./bin/notation plugin install --file ~/download/notation-azure-kv_1.0.1_darwin_amd64.tar.gz -d
DEBU[2024-01-18T12:55:26+08:00] Extracting file notation-azure-kv...         
DEBU[2024-01-18T12:55:26+08:00] Extracting file LICENSE...                   
DEBU[2024-01-18T12:55:26+08:00] Installing plugin from plugin path /tmp/notation-plugin2182206927 
DEBU[2024-01-18T12:55:26+08:00] Plugin get-plugin-metadata request: {}       
ERRO[2024-01-18T12:55:26+08:00] plugin get-plugin-metadata execution status: fork/exec /tmp/notation-plugin2182206927/notation-azure-kv: exec format error 
Error: plugin installation failed: failed to get metadata of new plugin: failed to execute the get-plugin-metadata command for plugin azure-kv.
Please ensure the plugin is executable and meet the installation requirements on the linux/amd64.
```

File: cmd/notation/plugin/install.go [hunk 2]
```diff
@@ -330,6 +331,23 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
 		if errors.As(err, &errPluginDowngrade) {
 			return fmt.Errorf("%w.\nIt is not recommended to install an older version. To force the installation, use the \"--force\" option", errPluginDowngrade)
 		}
+
+		var errExeFile plugin.PluginExecutableFileError
+		if errors.As(err, &errExeFile) {
+			var errPath *os.PathError
+			if errors.As(errExeFile, &errPath) && errPath.Op == "fork/exec" {
+				return fmt.Errorf("%s.\nPlease ensure the plugin is executable and meet the installation requirements on the %s/%s.",
```
Comment (Two-Hearts) [inline cmd/notation/plugin/install.go:339]: nit:
```suggestion
				return fmt.Errorf("%s.\nPlease ensure the plugin is executable and meet the installation requirements on %s/%s",
```

File: cmd/notation/plugin/install.go [hunk 3]
```diff
@@ -330,6 +331,23 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
...
+					// hide the wrapped error message to simplify the output
+					strings.TrimSuffix(strings.Split(errExeFile.Error(), "fork/exec")[0], ": "),
```
Comment (Two-Hearts) [inline cmd/notation/plugin/install.go:341]: consider using `strings.Cut(errExeFile.Error(), ': fork/exec')`

Comment (Two-Hearts) [reply cmd/notation/plugin/install.go:341]: Based on offline discussion, the `plugin.PluginExecutableFileError` should be updated to include an `innerError`.

**Review by Two-Hearts — DISMISSED** [review]
LGTM

File: go.mod [hunk 4]
```diff
@@ -25,8 +25,10 @@ require (
...
 	github.com/veraison/go-cose v1.1.0 // indirect
 	github.com/x448/float16 v0.8.4 // indirect
-	golang.org/x/crypto v0.17.0 // indirect
+	golang.org/x/crypto v0.18.0 // indirect
 	golang.org/x/mod v0.14.0 // indirect
 	golang.org/x/sync v0.4.0 // indirect
 	golang.org/x/sys v0.16.0 // indirect
 )
+
+replace github.com/notaryproject/notation-go => github.com/JeyJeyGao/notation-go v1.0.0-rc.6.0.20240118060847-73d28729ce20
```
Comment (Two-Hearts) [inline go.mod:34]: This need to be updated after the notation-go PR is merged.

File: cmd/notation/plugin/install.go [hunk 5]
```diff
@@ -330,6 +331,16 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
...
 		}
+
+		var errExeFile *plugin.PluginExecutableFileError
+		if errors.As(err, &errExeFile) {
+			return fmt.Errorf("%w.\nPlease ensure the plugin is executable on %s/%s.", err, runtime.GOOS, runtime.GOARCH)
+		}
+
+		var errMalformedPlugin *plugin.PluginMalformedError
+		if errors.As(err, &errMalformedPlugin) {
+			return fmt.Errorf("%w.\nPlease ensure to install the plugin for %s/%s. Contact the plugin publisher if the plugin executable file is malformed.", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
```
Comment (yizha1) [inline cmd/notation/plugin/install.go:342]:
```suggestion
			return fmt.Errorf("%w.\nThe plugin is not compatible with platform %s and architecture %s. Contact the plugin publisher if the plugin executable file is malformed.", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
```

Comment (yizha1) [reply cmd/notation/plugin/install.go:342]: @Two-Hearts Is this error message better?

Comment (Two-Hearts) [reply cmd/notation/plugin/install.go:342]: @yizha1 This is not necessarily true. The platform and arch can be correct, but the plugin executable file itself might be malformed.

File: cmd/notation/plugin/install.go [hunk 6]
```diff
@@ -330,6 +331,16 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
 		if errors.As(err, &errPluginDowngrade) {
 			return fmt.Errorf("%w.\nIt is not recommended to install an older version. To force the installation, use the \"--force\" option", errPluginDowngrade)
 		}
+
+		var errExeFile *plugin.PluginExecutableFileError
+		if errors.As(err, &errExeFile) {
+			return fmt.Errorf("%w.\nPlease ensure the plugin is executable on %s/%s.", err, runtime.GOOS, runtime.GOARCH)
```
Comment (priteshbandi) [inline cmd/notation/plugin/install.go:337]: Please ensure that plugin is compatible for %s/%s architecture and has correct file permissions.
```suggestion
			return fmt.Errorf("%w.\n"Please ensure that the plugin executable is compatible with the %s/%s architecture and has the appropriate file permissions.", err, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/install.go (hunk 5 above)
Comment (priteshbandi) [inline cmd/notation/plugin/install.go:342]:
```suggestion
			return fmt.Errorf("%w.\n The %s plugin is malformed. Please contact the plugin publisher for assistance.", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/list.go [hunk 7]
```diff
@@ -44,6 +45,11 @@ func listPlugins(command *cobra.Command) error {
 	mgr := plugin.NewCLIManager(dir.PluginFS())
 	pluginNames, err := mgr.List(command.Context())
 	if err != nil {
+		var errPluginDirWalk plugin.PluginDirectoryWalkError
+		if errors.As(err, &errPluginDirWalk) {
+			pluginDir, _ := dir.PluginFS().SysPath("")
+			return fmt.Errorf("%w.\nPlease check if the current user has access to the plugin directory: %s", errPluginDirWalk, pluginDir)
```
Comment (priteshbandi) [inline cmd/notation/plugin/list.go:51]:
```suggestion
			return fmt.Errorf("%w.\nPlease ensure that the current user has permission to access the plugin directory: %s", errPluginDirWalk, pluginDir)
```

File: cmd/notation/plugin/install.go (hunk 5 above)
Comment (Two-Hearts) [reply cmd/notation/plugin/install.go:342]: @priteshbandi There are two circumstances that can trigger `PluginMalformedError`:
1. `User error`: the user is trying to install a plugin for another arch. For example, installing `arm64` plugin file on `amd64` arch. In this case, the plugin itself is not malformed, the user needs to install the correct file.
2. `Plugin publisher error`: the plugin publisher published a plugin that's not following Notary project's spec. For example, notation cannot unmarshal the plugin response. In this case, the plugin itself is malformed, and the only actionable suggestion from Notation CLI is to contact the plugin publisher.

Given above, my suggestion is:
```suggestion
			return fmt.Errorf("%w.\nPlease ensure that the plugin executable file is intact and compatible with %s/%s. Contact the plugin publisher for further assistance.", errMalformedPlugin, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/install.go (hunk 6 above)
Comment (Two-Hearts) [reply cmd/notation/plugin/install.go:337]: @priteshbandi I think it's a bit verbose? How about
```suggestion
			return fmt.Errorf("%w.\nPlease ensure that the plugin executable file is compatible with %s/%s and has the appropriate file permissions.", err, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/install.go (hunk 5 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/install.go:342]:
```
./bin/notation plugin install --url https://github.com/Azure/notation-azure-kv/releases/download/v1.0.1/notation-azure-kv_1.0.1_linux_arm64.tar.gz --sha256sum d6b4be3cef6a5cb154ddd73f7bdc83f5d7e913e3b72eb88f7a5f82872ca63a5a -d
Downloading plugin from https://github.com/Azure/notation-azure-kv/releases/download/v1.0.1/notation-azure-kv_1.0.1_linux_arm64.tar.gz
Download completed
DEBU[2024-01-19T09:40:05+08:00] Extracting file notation-azure-kv...         
DEBU[2024-01-19T09:40:05+08:00] Extracting file LICENSE...                   
DEBU[2024-01-19T09:40:05+08:00] Installing plugin from path /tmp/notation-plugin1234095091 
DEBU[2024-01-19T09:40:05+08:00] Plugin get-plugin-metadata request: {}       
ERRO[2024-01-19T09:40:05+08:00] plugin get-plugin-metadata execution status: exit status 255 
Error: plugin installation failed: failed to execute the get-plugin-metadata command for plugin azure-kv: qemu-aarch64: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory.
Please ensure to install the plugin for linux/amd64. Contact the plugin publisher if the plugin executable file is malformed.
```

I encountered an error: 'qemu-aarch64: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory', which was classified as `PluginMalformedError`. This classification occurred because the error was returned from `stderr`. The error arose due to the user enabling the ARM qemu emulator without installing the required library on a x64 machine. In other words, a PluginMalformedError may also be caused by an architecture mismatch issue. Therefore, it is useful to include the `platform/Architecture` in the message to assist users in debugging the issue.

File: cmd/notation/plugin/list.go (hunk 7 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/list.go]: Updated.

File: cmd/notation/plugin/install.go [hunk 8]
```diff
@@ -330,6 +331,16 @@ func installPluginWithOptions(ctx context.Context, opts plugin.CLIInstallOptions
 		if errors.As(err, &errPluginDowngrade) {
 			return fmt.Errorf("%w.\nIt is not recommended to install an older version. To force the installation, use the \"--force\" option", errPluginDowngrade)
 		}
+
+		var errExeFile *plugin.PluginExecutableFileError
+		if errors.As(err, &errExeFile) {
+			return fmt.Errorf("%w.\nPlease ensure that the plugin executable is compatible with the %s/%s architecture and has the appropriate file permissions.", err, runtime.GOOS, runtime.GOARCH)
```
Comment (Two-Hearts) [inline cmd/notation/plugin/install.go:337]: I think it's a bit verbose? How about
```suggestion
			return fmt.Errorf("%w.\nPlease ensure that the plugin executable file is compatible with %s/%s and has appropriate permissions.", err, runtime.GOOS, runtime.GOARCH)
```

File: cmd/notation/plugin/install.go (hunk 6 above)
Comment (JeyJeyGao) [reply cmd/notation/plugin/install.go]: Updated to be `Please ensure that the plugin executable file is compatible with %s/%s and has appropriate permissions.`  for conciseness.

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM
